[package]
name = "maybe-owned"
version = "0.1.0"
authors = ["Philipp korber <philippkorber@gmail.com>"]
description = "provides a `MaybeOwned<'a,T>` enum with `From<T>` and `From<&'a T>`, different to `Cow` it does not require `ToOwned`"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dathinab/maybe-owned"
readme = "./README.md"
categories = []
keywords = [
    "maybe", "owned", "Cow"
]


[badges]
travis-ci = { repository = "dathinab/maybe-owned", branch = "master" }
