[package]
name = "maybe-owned"
version = "0.3.0"
authors = [
	"Philipp korber <philippkorber@gmail.com>",
	"darkstalker <slayerbeast@gmail.com>"
]
description = "provides a `MaybeOwned<'a,T>` type different to std's `Cow` it implements `From<T>` and `From<&'a T>` and does not require `ToOwned`"
license = "MIT OR Apache-2.0"
repository = "https://github.com/dathinab/maybe-owned"
readme = "./README.md"
categories = []
keywords = [
    "maybe", "owned", "Cow"
]


[badges]
travis-ci = { repository = "dathinab/maybe-owned", branch = "master" }

[dependencies]
serde = { version = "1", optional = true }
